---
title: "Create Single-Cell Experiment for PDGFRb+ dataset"
author: "Javier Perales-Paton - javier.perales@bioquant.uni-heidelberg.de"
output: github_document
---

## Setting the environment

### Internal variables
```{r}
set.seed(1234)
OUTDIR <- "./mouse_PDGFRBpositive_01_create_sce_output/";
if(!dir.exists(OUTDIR)) dir.create(OUTDIR, recursive = TRUE);
```

### Load libraries
```{r}
library("Matrix")
library("viper")
# library("gridExtra")
library("dplyr")
library("purrr")
library("SingleCellExperiment")
library("SummarizedExperiment")
library("scran")
library("scater")
```

## Load data

```{r}
dat <- Matrix::readMM("../data/SmartSeq/log_expression.mtx")
rowDat <- read.table("../data/SmartSeq/log_expression_rowData.txt",sep="\t",header=TRUE)
colDat <- read.table("../data/SmartSeq/log_expression_colData.txt", sep="\t",header=TRUE)

# Genes
rownames(dat) <- rowDat$x
rownames(rowDat) <- rowDat$x

# Cells
colnames(dat) <- paste0("cell",1:ncol(dat))
rownames(colDat) <- paste0("cell",1:ncol(dat))

rm(rowDat)
## In the end we do not use single-cell experiments but multi-assay
# # Create single-cell experiment object
# dat <- SingleCellExperiment(assays = list(logcounts = dat),
# 			    colData=colDat,
# 			    rowData=rowDat)
# rm(dat, rowDat, colDat)
```

Summary of cell metadata
```{r}
summary(as.data.frame(colDat))
```

## Functional characterization

### Inference of Transcription Factor activities
```{r dorothea}
# load regulons
df2regulon <- function(df, regulator_name="tf") {
  regulon = df %>% split(.[regulator_name]) %>% map(function(dat) {
    targets = setNames(dat$mor, dat$target)
    likelihood = dat$likelihood
    list(tfmode = targets, likelihood = likelihood)
  })
  return(regulon)
}

regulon.df <- read.table("../data/Prior/dorothea_regulon_mouse_v1.csv", sep=",", header=TRUE, stringsAsFactors = FALSE)
regulon.df <- regulon.df[regulon.df$confidence %in% c("A","B","C"),]
regul <- df2regulon(df=regulon.df)

# Calculate TF activities
TF <- viper(eset = as.matrix(dat), regulon = regul,
              nes = T, method = "scale", minsize = 4,
              eset.filter = F, adaptive.size = F, verbose=FALSE)
  
```

### Inference of Pathway activities
```{r progeny}
progeny.mat <- read.table("../data/Prior/progeny_matrix_mouse_v1.txt",sep=",",header=TRUE)
rownames(progeny.mat) <- progeny.mat$X
progeny.mat <- progeny.mat[which(colnames(progeny.mat)!="X")]
progeny.mat <- as.matrix(progeny.mat)

common <- intersect(rownames(dat), rownames(progeny.mat))
  
prog <- t(as.matrix(dat[common,])) %*% progeny.mat[common,]
rn <- rownames(prog)
prog <- apply(prog,2,scale)
rownames(prog) <- rn
prog <- t(prog)
  
stopifnot(colnames(dat) == colnames(prog))
```

## Create a Single-Cell Experiment

```{r}

colDat$Time.point <- factor(as.character(colDat$Time.point),
			 levels=c("Uninjured","Day 2 UUO", "Day 10 UUO"))
sce <- SingleCellExperiment(assays=list("logcounts"=dat),
			    colData=colDat,
			    altExps=list("pathway"=SummarizedExperiment(assays=list("pathway"=prog)),
					 "TF"=SummarizedExperiment(assays=list("TF"=TF)))
			    )

## Alternative: MultiAssayExperiment
# library("MultiAssayExperiment")
# mdat <- MultiAssayExperiment(experiments=list("logcounts"=dat,
# 					      "pathways"=prog,
# 					      "TF"=TF),
# 			     colData=colDat)
# rm(dat,prog,TF,colDat)
# 
# #NOTE: How to access?
```

## Save data

```{r}
saveRDS(sce, file=paste0(OUTDIR,"/sce.rds"))
```

## SessionInfo
```{r}
sessionInfo()

{                                                                                                                                                                                                           
sink(file=paste0(OUTDIR,"/sessionInfo.txt"))
print(sessionInfo())
sink()
}
```
